name: Update DAG

on:
  workflow_dispatch:

jobs:
  modify_file:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout repository
      # uses: actions/checkout@v2
      # with:
        # ref: main
        # repository: zabayek/variables
        # path: variables
        # token: ${{ secrets.REPO_ACCESS_TOKEN }}
       
    # repo *actions_testing*
    - name: Checkout repository *actions_testing*
      uses: actions/checkout@v2
      with:
        ref: main
        # path: actions_testing
        # repository: other_repo_owner/other_repo_name
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Repo Tag to variable
      run: |
        currentVersion=$GITHUB_REF_NAME
        echo $currentVersion
    # repo *variables*
    - name: Checkout repository *variables*
      uses: actions/checkout@v2
      with:
        ref: main
        path: variables
        repository: zabayek/variables
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Run Python script
      run: |
        ls -a
        echo $currentVersion
        echo $GITHUB_REF_NAME
        python3 scripts/update_dag.py -dag_file dag.json -rm_file "./variables/.helm/ecco_cdp_gold_retailmanagement.json" -proj_ver $GITHUB_REF_NAME

    - name: Create new branch
      run: |
        BRANCH_NAME=modify-a-json-$(date +%s)
        git checkout -b $BRANCH_NAME
        git status
        git branch
        git add "./variables/.helm/ecco_cdp_gold_retailmanagement.json"
#       git commit -m "Update variables with latest version of repository 2"
#       git push origin $BRANCH_NAME

#    - name: Commit changes
#      uses: elucid/action-git-auto-commit@v1
#      with:
#        repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}
#        commit_message: "Modify a.json file and create a new branch"
