name: Modify a.json and create a new branch

on:
  workflow_dispatch:

jobs:
  modify_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2 
      with:
        ref: main
        repository: other_repo_owner/other_repo_name
        token: ${{ secrets.REPO_ACCESS_TOKEN }}        

    - name: GitHub Tag Name example
      run: |
        echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        echo "Tag from internet: $(git describe --tags --abbrev=7)"