name: Update ver & DAG graph

on:
  workflow_dispatch:

jobs:
  modify_file:
    runs-on: ubuntu-latest

    steps:
      
    # repo *actions_testing*
    - name: Checkout repository *actions_testing*
      uses: actions/checkout@v2
      with:
        ref: main
        # path: actions_testing
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    # repo *variables*
    - name: Checkout repository *variables*
      uses: actions/checkout@v2
      with:
        ref: main
        path: variables
        repository: zabayek/variables
        token: ${{ secrets.REPO_ACCESS_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Run Python script
      run: |
        ls -a
        echo "Project version: ${GITHUB_REF_NAME}"
        python3 scripts/update_dag.py -dag_file dag.json -rm_file "./variables/.helm/ecco_cdp_gold_retailmanagement.json" -proj_ver $GITHUB_REF_NAME

    - name: Create new branch
      run: |
        cd variables
        cat "./.helm/ecco_cdp_gold_retailmanagement.json"
        BRANCH_NAME=modify_dag_and_ver-${GITHUB_REF_NAME}
        git checkout -b $BRANCH_NAME
        # git status
        # git branch
        git add ./.helm/ecco_cdp_gold_retailmanagement.json
        echo "$(git config user.email)"

#        git config --local user.email "$(git config user.email)"
#        git config --local user.name "$(git config user.name)"
        
        git config --local user.email "psab@ecco.com"
        git config --local user.name "zabayek"
        git commit -m "Update airflow-variables"
        git push origin $BRANCH_NAME
#       git commit -m "Update variables with latest version of repository 2"
#       git push origin $BRANCH_NAME

#    - name: Commit changes
#      uses: elucid/action-git-auto-commit@v1
#      with:
#        repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}
#        commit_message: "Modify a.json file and create a new branch"
