name: Update ver & DAG graph

on:
  workflow_dispatch:

jobs:
  modify_file:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: get secretes
      uses: hashicorp/vault-action@v2.4.1
      with:
        url: https://hashicorp-vault.production.sneaksanddata.com/
        role: github
        method: jwt
        secrets: |
          /secret/data/repositories/ecco-cdp-gold-retailmanagement ACTIONS_TESTING_KEY ;
          /secret/data/repositories/ecco-cdp-gold-retailmanagement VARIABLES_KEY ;
    # repo *actions_testing*
    - name: Checkout repository *actions_testing*
      uses: actions/checkout@v2
      with:
        ref: main
        # path: actions_testing
        token: ${{ env.ACTIONS_TESTING_KEY }}

    # repo *variables*
    - name: Checkout repository *variables*
      uses: actions/checkout@v2
      with:
        ref: main
        path: variables
        repository: zabayek/variables
        token: ${{ env.VARIABLES_KEY }}

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
    - name: Run Python script
      run: |
        ls -a
        echo "Project version: ${GITHUB_REF_NAME}"
        python3 scripts/update_dag.py -dag_file dag.json -rm_file "./variables/.helm/ecco_cdp_gold_retailmanagement.json" -proj_ver $GITHUB_REF_NAME
        cat "./variables/.helm/ecco_cdp_gold_retailmanagement.json"

    - name: Create new branch
      run: |
        cd variables
        BRANCH_NAME=modify_dag_and_ver-${GITHUB_REF_NAME}
        git checkout -b $BRANCH_NAME
        git add ./.helm/ecco_cdp_gold_retailmanagement.json
        git config --local user.email "deploy-helper@ecco.com"
        git config --local user.name "deploy-helper"
        git commit -m "Update airflow-variables"
        git push origin $BRANCH_NAME
#       git commit -m "Update variables with latest version of repository 2"
#       git push origin $BRANCH_NAME

#    - name: Commit changes
#      uses: elucid/action-git-auto-commit@v1
#      with:
#        repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}
#        commit_message: "Modify a.json file and create a new branch"
